defaults: &defaults
  :site:
    :site_name: "My Site"
    :header: "A cool site, coming soon!"
    :tagline: "Yes! We will be launching very, very, very soon!"
    :email: mailto:me@localhost  # mailto: must be kept here to make it a link
    :facebook: deanpcmad
    :twitter: deanperry
    :skype: deanpcmad
    
  :css_file: style.css
  
  :theme: theme1

  :slider_enable: true  # true to enable slider or false to disable it
  :slider_effect_duration: 2000  # how long should the slider transition effect (fade) last? 1 second = 1000
  :slider_duration: 8000  # how long should one image be shown? This does not affect the above transition duration.
  
  :slider_image1: slider/1.jpg
  :slider_image2: slider/2.jpg
  :slider_image3: slider/3.jpg
  :slider_image4: slider/4.jpg
  :slider_image5: slider/5.jpg
  
  :launch_enable: true # true to enable countdown or nothing to disable it
  :launch_year: 2020
  :launch_month: 12  # be aware, because the first month (january) counts as 0. For this reason the 4th month in this case would be not april but may, and the last month is 11 for december.
  :launch_day: 8
  :launch_hour: 12
  :launch_minutes: 30
  :launch_progress:  # to disable the launch progress bar, don't enter anything here.
  
  # To enable campaign_monitor or mail_chimp enter 'true' into either of them. If you put 'false' it will still show.
  :campaign_monitor: false
  :campaign_monitor_url: "user"  

    
  :mail_chimp: true
  :mail_chimp_url: "user"  # This is the url in the form action. You may just need to change to your username
  :mail_chimp_hidden_u: "c5f92ebdb48215432jdb7761f"
  :mail_chimp_hidden_id: "eae4dded6e"
  :mail_chimp_server_id: "us2"
  

  :analytics:
    :google: ""  # enter google analytics ID - e.g. UA-1030849-93
  

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
